version: '3.6'
services:
  postgres:
    image: postgres:14.5    
    container_name: postgres-financials-db
    restart: always
    ports:
      - '5432:5432' # expose pg on port 5932 to not collide with pg from elswhere
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financials

volumes:
  db_data:
