services:
  postgres:
    image: postgres:14.5    
    container_name: postgres-financials-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financials"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - financials-network

  # mcp-postgres:
  #   image: mcp/postgres:latest
  #   container_name: mcp-postgres-server
  #   restart: always
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - MCP_SERVER_PORT=3001
  #     - MCP_SERVER_HOST=0.0.0.0
  #    # The application's entrypoint will receive this URL as its first argument.
  #   command: ["postgresql://postgres:postgres@postgres:5432/financials"]
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - financials-network

volumes:
  db_data:

networks:
  financials-network:
    driver: bridge
