import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'My Financials',
  description: 'Generated by create-t3-app',
  icons: { icon: '/favicon.ico' },
};

export default function HomePage() {
  return <main className='bg-gray-50'>My HomePage</main>;
}
