import AuthorizedLayout from '@/layouts/AuthorizedLayout';
import type { NextLayoutComponentType } from 'next';
import Head from 'next/head';
import type { ReactElement } from 'react';

const HomePage: NextLayoutComponentType = () => {
  return (
    <>
      <Head>
        <title>My Financials App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-50'>My HomePage</main>
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <AuthorizedLayout>{page}</AuthorizedLayout>;
};

export default HomePage;
