import { type NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import PageLoading from '@/components/PageLoading';
import { useSession } from 'next-auth/react';
import Hero from '@/layouts/Hero';

const LandingPage: NextPage = () => {
  const router = useRouter();
  const { status } = useSession();

  const data = {
    hero: {
      appType: 'My Financials App',
      tagLine: 'Keep your financials in check',
      description:
        'An app to track your financial position and spendings. Moreover to help you calculate your annual zakat liabilities',
      mainActionText: 'Sign in',
      extraActionText: 'Sign up',
      showActionButtons: true,
    },
  };

  if (status === 'loading') {
    return <PageLoading />;
  }

  if (status === 'authenticated') {
    router.replace('/home');
    return null;
  }
  return (
    <>
      <Head>
        <title>My Financials App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-50'>
        <Hero
          appType={data.hero.appType}
          tagLine={data.hero.tagLine}
          description={data.hero.description}
          mainActionText={data.hero.mainActionText}
          extraActionText={data.hero.extraActionText}
          showActionButtons={data.hero.showActionButtons}
        />
      </main>
    </>
  );
};

export default LandingPage;
