function featureSourcePath(featureId, fileName) {
  const [domain, ...featureParts] = String(featureId ?? '').split('.');
  const feature = featureParts.join('.');
  return `spec/${domain}/${feature}/${fileName}`;
}

export function renderCapsule(data) {
  const ownsSection = renderOwnsSection(data.owns ?? {});
  const invariantsSection = renderInvariantsSection(Array.isArray(data.invariants) ? data.invariants : []);
  const consumedBySection = renderConsumedBySection(Array.isArray(data.consumedBy) ? data.consumedBy : []);
  const gatesSection = renderGatesSection(Array.isArray(data.gates) ? data.gates : []);
  const referencesSection = renderReferencesSection(Array.isArray(data.references) ? data.references : []);

  return [
    `# ${data.featureId} — Capsule`,
    '',
    `<!-- GENERATED by scripts/harness/capsule-format/generate.mjs`,
    `     SOURCE-SHA: ${data.sourceSha}`,
    `     TOKENS: ${data.tokens}/800 -->`,
    '',
    '## Purpose',
    data.purpose || '_None._',
    '',
    '## Owns',
    ownsSection,
    '',
    '## Invariants',
    invariantsSection,
    '',
    '## Consumed by',
    consumedBySection,
    '',
    '## Gates',
    gatesSection,
    '',
    '## Deeper context',
    `- Context: [${featureSourcePath(data.featureId, 'context.md')}](./context.md)`,
    `- LLD: [${featureSourcePath(data.featureId, 'lld.md')}](./lld.md)`,
    ...referencesSection,
  ].join('\n');
}

const MAX_ENTRIES_PER_BUCKET = 5;

function renderOwnsSection(owns) {
  const buckets = ['routers', 'services', 'components', 'app', 'tests'];
  const lines = [];

  for (const bucket of buckets) {
    const entries = Array.isArray(owns[bucket]) ? owns[bucket].filter(Boolean) : [];
    if (entries.length === 0) continue;
    const shown = entries.slice(0, MAX_ENTRIES_PER_BUCKET);
    const remainder = entries.length - shown.length;
    let value = shown.map((entry) => `\`${entry}\``).join(', ');
    if (remainder > 0) value += `, …and ${remainder} more`;
    lines.push(`- **${bucket}** — ${value}`);
  }

  return lines.length ? lines.join('\n') : '_None._';
}

function renderInvariantsSection(invariants) {
  if (invariants.length === 0) return '_None declared._';
  return invariants.map((item, index) => `${index + 1}. ${item}`).join('\n');
}

function renderConsumedBySection(consumedBy) {
  if (consumedBy.length === 0) return '_None._';
  const top = consumedBy.slice(0, 5);
  const remainder = consumedBy.length - top.length;
  const lines = top.map((id) => `- ${id}`);
  if (remainder > 0) {
    lines.push(`- …and ${remainder} more — see spec/index.json`);
  }
  return lines.join('\n');
}

function renderGatesSection(gates) {
  if (gates.length === 0) return '_None._';
  return gates.map((gate) => `- \`${gate}\``).join('\n');
}

function renderReferencesSection(references) {
  if (references.length === 0) return [];
  return references.map((reference) => {
    const value = String(reference ?? '').trim();
    if (!value) return '';
    if (/^\[[^\]]+\]\([^)]+\)$/.test(value)) return `- ${value}`;
    return `- [${value}](${value})`;
  }).filter(Boolean);
}
